import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { execFileSync } from 'node:child_process';
import { buildSite } from './build-site.mjs';
const git = (cwd, ...args) => execFileSync('git', ['-C', cwd, ...args], { stdio: 'pipe' }).toString().trim();
const put = (root, path, text) => { mkdirSync(join(root, path, '..'), {recursive:true}); writeFileSync(join(root,path),text); };
test('primary site build publishes committed runtime files only, with a primary manifest', () => {
  const src=mkdtempSync(join(tmpdir(),'mynecraft-site-test-'));
  git(src,'init','-b','main'); git(src,'config','user.name','Site test'); git(src,'config','user.email','test@example.invalid'); git(src,'config','core.autocrlf','false');
  for(const file of ['index.html','game/mynecraft.html','game/start-menu.css','game/assets/test.svg','game/tests/private.test.mjs','AGENTS.md']) put(src,file,'source '+file+'\n');
  git(src,'add','.'); git(src,'commit','-m','fixture');
  put(src,'game/mynecraft.html','uncommitted edit\n');
  const result=buildSite(src,join(src,'_site'));
  assert.equal(result.runtimeFiles,4);
  assert.equal(readFileSync(join(src,'_site/game/mynecraft.html'),'utf8'),'source game/mynecraft.html\n');
  assert.equal(existsSync(join(src,'_site/game/tests')),false);
  assert.equal(existsSync(join(src,'_site/AGENTS.md')),false);
  assert.equal(existsSync(join(src,'_site/.nojekyll')),true);
  const manifest=JSON.parse(readFileSync(join(src,'_site/mynecraft-release.json'),'utf8'));
  assert.equal(manifest.liveBase,'https://percycodesios.github.io/MYnecraft/');
  assert.equal(manifest.compatibilityBase,'https://percycodesios.github.io/CyberGrader.io/');
  assert.equal(Object.keys(manifest.files).length,4);
  assert.throws(()=>buildSite(src,join(src,'_site')),/empty/);
  assert.throws(()=>buildSite(src,join(src,'game')),/top-level/);
  assert.throws(()=>buildSite(src,join(src,'..','outside')),/top-level/);
});
